let allFeats = [
  {"name":"Actor","scores":"charisma"},
  {"name":"Alert","scores":""},
  {"name":"Artificer Initiate","scores":""},
  {"name":"Athlete","scores":"dexterity strength"},
  {"name":"Charger","scores":""},
  {"name":"Chef","scores":"constitution wisdom"},
  {"name":"Crossbow Expert","scores":""},
  {"name":"Crusher","scores":"strength constitution"},
  {"name":"Defensive Duelist","scores":""},
  {"name":"Dual Wielder","scores":""},
  {"name":"Dungeon Delver","scores":""},
  {"name":"Durable","scores":"constitution"},
  {"name":"Eldritch Adept","scores":""},
  {"name":"Elemental Adept","scores":""},
  {"name":"Fey Touched","scores":"intelligence wisdom charisma"},
  {"name":"Fighting Initiate","scores":""},
  {"name":"Grappler","scores":""},
  {"name":"Great Weapon Master","scores":""},
  {"name":"Gunner","scores":"dexterity"},
  {"name":"Healer","scores":""},
  {"name":"Heavily Armored","scores":"strength"},
  {"name":"Heavy Armor Master","scores":"strength"},
  {"name":"Inspiring Leader","scores":""},
  {"name":"Keen Mind","scores":"intelligence"},
  {"name":"Lightly Armored","scores":"strength dexterity"},
  {"name":"Linguist","scores":"intelligence"},
  {"name":"Lucky","scores":""},
  {"name":"Mage Slayer","scores":""},
  {"name":"Magic Initiate","scores":""},
  {"name":"Martial Adept","scores":""},
  {"name":"Medium Armor Master","scores":""},
  {"name":"Metamagic Adept","scores":""},
  {"name":"Mobile","scores":""},
  {"name":"Moderately Armored","scores":"strength dexterity"},
  {"name":"Mounted Combatent","scores":""},
  {"name":"Observant","scores":"wisdom intelligence"},
  {"name":"Piercer","scores":"strength dexterity"},
  {"name":"Poisoner","scores":""},
  {"name":"Polearm Master","scores":""},
  {"name":"Resilient","scores":"strength dexterity constitution wisdom intelligence charisma"},
  {"name":"Ritual Caster","scores":""},
  {"name":"Savage Attacker","scores":""},
  {"name":"Sentinel","scores":""},
  {"name":"Shadow Touched","scores":"intelligence wisdom charisma"},
  {"name":"Sharpshooter","scores":""},
  {"name":"Shield Master","scores":""},
  {"name":"Skill Expert","scores":"strength dexterity constitution wisdom intelligence charisma"},
  {"name":"Skilled","scores":""},
  {"name":"Skulker","scores":""},
  {"name":"Slasher","scores":"strength dexterity"},
  {"name":"Spell Sniper","scores":""},
  {"name":"Tavern Brawler","scores":"strength constitution"},
  {"name":"Telekinetic","scores":"intelligence wisdom charisma"},
  {"name":"Telepathic","scores":"intelligence wisdom charisma"},
  {"name":"Tough","scores":""},
  {"name":"War Caster","scores":""},
  {"name":"Weapon Master","scores":"strength dexterity"}
]